import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header'
import Hero from '../components/Hero'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Loki</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <div className='animatebg h-full w-full sm:px-16 px-6 overflow-hidden'>

        <Header />

        <Hero />
      </div>
    </div>
  )
}
